///////////////////////////////////////////////////////////
//  Ház.cs
//  Implementation of the Class Ház
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:56
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;


namespace CampLogic.TaborvezetoFunkciok
{
    public class Haz
    {

        public Haz()
        {

        }


        #region Adat kapcsolati tulajdonságok

        [Key]
        public int HázId { get; set; }

        public virtual List<Szoba> Szobak { get; set; }

        #endregion


        public int MapX { get; set; }

        public int MapY { get; set; }

        public string Név { get; set; }

        public override string ToString()
        {
            return Név + " { " + MapX + "; " + MapY + " } (" + HázId + ")";
        }

    }//end Ház

}//end namespace TáborvezetõFunkciók