///////////////////////////////////////////////////////////
//  Statisztika.cs
//  Implementation of the Class Statisztika
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:56
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



namespace CampLogic.TaborvezetoFunkciok
{
    public class Statisztika
    {

        public Statisztika()
        {
            Oszlopnevek = new List<string>();
            Sorok = new List<List<string>>();
        }


        public Statisztika(List<string> oszlopnevek, List<List<string>> sorok)
        {
            Oszlopnevek = oszlopnevek;
            Sorok = sorok;
        }

        public List<string> Oszlopnevek { get; set; }

        public List<List<string>> Sorok { get; set; }

    }//end Statisztika

}//end namespace TáborvezetõFunkciók