///////////////////////////////////////////////////////////
//  SzobaKezelõ.cs
//  Implementation of the Class SzobaKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:56
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using CampLogic.TaborvezetoFunkciok;
using CampLogic.Db;
namespace CampLogic.TaborvezetoFunkciok
{
    public class SzobaKezelo
    {

        MyDbConnection conn = new MyDbConnection();

        public SzobaKezelo()
        {

        }


        /// 
        /// <param name="haz"></param>
        /// <param name="szoba"></param>
        public bool SzobaLetrehozas(Haz haz, Szoba szoba)
        {

            /*
             *  Hibakezelés új szoba szobaszáma nem lehet azonos, egy az adott házban korábban felvett szobáéval
             */
            if (haz.Szobak!=null && haz.Szobak.Exists(m => m.Szobaszam == szoba.Szobaszam))
            {
                return false;
            }

           
            szoba.Ház = conn.Hazak.Find(haz.HázId);

            conn.Szobak.Add(szoba);

            conn.SaveChanges();

            return true;
        }

        public List<Szoba> SzobaListazas()
        {
            return (from k in conn.Szobak select k).ToList<Szoba>();
        }

        public List<Szoba> SzobaListazas(Haz haz)
        {
            return (from k in conn.Szobak where k.Ház == haz select k).ToList<Szoba>();
        }

        /// 
        /// <param name="ház"></param>
        /// <param name="szoba"></param>
        public bool SzobaModositas(Haz haz, Szoba szoba)
        {
            szoba.Ház = conn.Hazak.Find(haz.HázId);
            conn.SaveChanges();
            return true;
        }

        /// 
        /// <param name="szoba"></param>
        public bool SzobaTorles(Szoba szoba)
        {
            conn.Szobak.Remove(szoba);
            conn.SaveChanges();

            return true;
        }

    }//end SzobaKezelõ

}//end namespace TáborvezetõFunkciók