///////////////////////////////////////////////////////////
//  Szoba.cs
//  Implementation of the Class Szoba
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:56
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;


using CampLogic.TaborvezetoFunkciok;
using CampLogic.IfjusagiVezetoFunkciok;
namespace CampLogic.TaborvezetoFunkciok
{
    public class Szoba
    {

        public Szoba()
        {

        }


        #region Adat kapcsolati tulajdonságok
       
        [Key]
        public int SzobaId { get; set; }

        public virtual Haz Haz { get; set; }


        #endregion


        public int Ferohely { get; set; }

        public string Szobaszam { get; set; }

        public virtual List<Taborozo> Taborozok { get; set; }

        public override string ToString()
        {
            return Szobaszam + " ( " + Ferohely + " ) Ház: "+ Haz.Nev;
        }

    }//end Szoba

}//end namespace TáborvezetõFunkciók