///////////////////////////////////////////////////////////
//  HázKezelõ.cs
//  Implementation of the Class HázKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:56
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using Db;
namespace TáborvezetõFunkciók
{
    public class HázKezelõ
    {


        public HázKezelõ()
        {

        }

        DbConnection conn = new DbConnection();

        /// 
        /// <param name="ház"></param>
        public bool HázLetrehozas(Ház ház)
        {

            int numH = (from k in conn.Házak
                        where k.Név == ház.Név
                        select k).Count();

            // ha valakinek jobban tetszik 
            //int numH = conn.Házak.Count(m => m.Név == ház.Név);


            /*
             * Két házat azonos névvel nem lehet felvenni
             */
            if (numH > 0)
            {
                return false;
            }

            conn.Házak.Add(ház);
            conn.SaveChanges();

            return true;
        }

        public List<Ház> HazListazas()
        {
            return (from k in conn.Házak select k).ToList<Ház>();
        }

        /// 
        /// <param name="ház"></param>
        /// 

        /*
         * A ListBox-ban, a DbConnect-bõl származó Ház volt, amit módosítottak is
         * Mivel referencia típus, elvileg az eredeti is módosúlt, így elég csak menteni a módosításokat
         */
        public bool HázModositas(Ház ház)
        {
            conn.SaveChanges();

            return true;
        }

        /// 
        /// <param name="haz"></param>
        public bool HazTorles(Ház haz)
        {

            /*
             * Olyan házat nem lehet törölni, melynek vannak még szobái, hisz 
             * a szobában Reference constraint van a ház-ra.
             */
            haz.Szobák.Clear();
            conn.SaveChanges();


            conn.Házak.Remove(haz);
            conn.SaveChanges();

            return true;
        }

    }//end HázKezelõ

}//end namespace TáborvezetõFunkciók