///////////////////////////////////////////////////////////
//  StatisztikaKazelõ.cs
//  Implementation of the Class StatisztikaKazelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:56
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


using CampLogic.TáborvezetõFunkciók;
using CampLogic.Db;
namespace CampLogic.TáborvezetõFunkciók
{
    public class StatisztikaKazelõ
    {

        MyDbConnection conn = new MyDbConnection();

        public StatisztikaKazelõ()
        {

        }

        public Statisztika HanyOrszagPerTurnus()
        {
            Statisztika ret = new Statisztika();

            ret.Oszlopnevek.Add("Turnusok");
            ret.Oszlopnevek.Add("Ország szám");

            var turnusok = (from t in conn.Turnusok select t);

            foreach (var turnus in turnusok)
            {
                int országszám = (from k in conn.Korcsoportok
                                  where k.TurnusId == turnus.TurnusId
                                  group k by k.Orszag).Count();

                List<string> sor = new List<string>();
                sor.Add(turnus.Nev);
                sor.Add(országszám.ToString());

                ret.Sorok.Add(sor);

            }

            return ret;
        }

        public Statisztika HanyTaborozóPerTurnus()
        {
            Statisztika ret = new Statisztika();

            var turnusok = (from t in conn.Turnusok select t);

            foreach (var turnus in turnusok)
            {

                int táborozószám = (from té in conn.Táborozók 
                                  join cs in conn.Csoportok on té.CsoportId equals cs.CoportId
                                  join kcs in conn.Korcsoportok on cs.Korcsoport equals kcs
                                  where kcs.TurnusId == turnus.TurnusId
                                  select té).Count();


                List<string> sor = new List<string>();
                sor.Add(turnus.Nev);
                sor.Add(táborozószám.ToString());

                ret.Sorok.Add(sor);
               
            }

            return ret;
        }

    }//end StatisztikaKazelõ

}//end namespace TáborvezetõFunkciók