///////////////////////////////////////////////////////////
//  SzobaKezelõ.cs
//  Implementation of the Class SzobaKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:56
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using TáborvezetõFunkciók;
using Db;
namespace TáborvezetõFunkciók
{
    public class SzobaKezelõ
    {

        DbConnection conn = new DbConnection();

        public SzobaKezelõ()
        {

        }


        /// 
        /// <param name="haz"></param>
        /// <param name="szoba"></param>
        public bool SzobaLetrehozas(Ház haz, Szoba szoba)
        {

            /*
             *  Hibakezelés új szoba szobaszáma nem lehet azonos, egy az adott házban korábban felvett szobáéval
             */
            if (haz.Szobák.Exists(m => m.Szobaszam == szoba.Szobaszam))
            {
                return false;
            }

            szoba.Ház = haz;

            conn.Szobák.Add(szoba);

            conn.SaveChanges();

            return true;
        }

        public List<Szoba> SzobaListazas()
        {
            return (from k in conn.Szobák select k).ToList<Szoba>();
        }

        public List<Szoba> SzobaListazas(Ház ház)
        {
            return (from k in conn.Szobák where k.Ház == ház select k).ToList<Szoba>();
        }

        /// 
        /// <param name="ház"></param>
        /// <param name="szoba"></param>
        public bool SzobaModositas(Ház ház, Szoba szoba)
        {
            conn.SaveChanges();
            return true;
        }

        /// 
        /// <param name="szoba"></param>
        public bool SzobaTorles(Szoba szoba)
        {
            conn.Szobák.Remove(szoba);
            conn.SaveChanges();

            return true;
        }

    }//end SzobaKezelõ

}//end namespace TáborvezetõFunkciók