///////////////////////////////////////////////////////////
//  Turnus.cs
//  Implementation of the Class Turnus
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:56
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;


using KorcsoportVezetõFunkciók;
namespace TáborvezetõFunkciók
{
    public class Turnus
    {


        public Turnus()
        {

        }


        #region Adat kapcsolati tulajdonságok

        [Key]
        public int TurnusId { get; set; }

        public virtual List<Korcsoport> Korcsoportok { get; set; }

        #endregion


        public bool Aktív { get; set; }

        public DateTime Befejezes { get; set; }

        public DateTime Kezdes { get; set; }

        

        public string Nev { get; set; }

        public int Sorszam { get; set; }



    }//end Turnus

}//end namespace TáborvezetõFunkciók