///////////////////////////////////////////////////////////
//  TurnusKezelõ.cs
//  Implementation of the Class TurnusKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:56
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using TáborvezetõFunkciók;
using Db;
namespace TáborvezetõFunkciók
{
    public class TurnusKezelõ
    {

        DbConnection conn = new DbConnection();

        public TurnusKezelõ()
        {

        }


        /// 
        /// <param name="turnus"></param>
        public bool TurnusLetrehozas(Turnus turnus)
        {

            conn.Turnusok.Add(turnus);
            conn.SaveChanges();

            return true;
        }

        public List<Turnus> TurnusListazas()
        {

            return (from k in conn.Turnusok select k).ToList<Turnus>();
        }

        /// 
        /// <param name="turnus"></param>
        public bool TurnusModositas(Turnus turnus)
        {
            conn.SaveChanges();
            return true;
        }

    }//end TurnusKezelõ

}//end namespace TáborvezetõFunkciók