///////////////////////////////////////////////////////////
//  ICsoportKezelõ.cs
//  Implementation of the Interface ICsoportKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:00
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



namespace CampLogic.KorcsoportVezetõFunkciók {
	public interface ICsoportKezelõ<T> {

		/// 
		/// <param name="csoport"></param>
		bool Letrehoz(T csoport);

		List<T> Listaz();

		/// 
		/// <param name="csoport"></param>
		bool Modosit(T csoport);

		/// 
		/// <param name="csoport"></param>
		bool Torol(T csoport);
	}//end ICsoportKezelõ

}//end namespace KorcsoportVezetõFunkciók