///////////////////////////////////////////////////////////
//  CsoportKezelõ.cs
//  Implementation of the Class CsoportKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:00
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using KorcsoportVezetõFunkciók;
using Db;
namespace KorcsoportVezetõFunkciók
{
    public class CsoportKezelõ : ICsoportKezelõ<CsoportKezelõ>
    {

        public DbConnection conn;

        public CsoportKezelõ()
        {

        }


        /// 
        /// <param name="korcsoport"></param>
        public List<Csoport> Listaz(Korcsoport korcsoport)
        {

            return null;
        }

        #region ICsoportKezelõ<CsoportKezelõ> Members

        /// 
        /// <param name="csoport"></param>
        public bool Letrehoz(CsoportKezelõ csoport)
        {
            throw new NotImplementedException();
        }

        List<CsoportKezelõ> ICsoportKezelõ<CsoportKezelõ>.Listaz()
        {
            throw new NotImplementedException();
        }

        /// 
        /// <param name="csoport"></param>
        public bool Modosit(CsoportKezelõ csoport)
        {
            throw new NotImplementedException();
        }

        /// 
        /// <param name="csoport"></param>
        public bool Torol(CsoportKezelõ csoport)
        {
            throw new NotImplementedException();
        }

        #endregion
    }//end CsoportKezelõ

}//end namespace KorcsoportVezetõFunkciók