///////////////////////////////////////////////////////////
//  KorcsoportKezelõ.cs
//  Implementation of the Class KorcsoportKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:00
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using KorcsoportVezetõFunkciók;
using Db;
namespace KorcsoportVezetõFunkciók {
	public class KorcsoportKezelõ : ICsoportKezelõ<KorcsoportKezelõ> {

		public DbConnection conn = new DbConnection();

		public KorcsoportKezelõ(){

		}


        #region ICsoportKezelõ<KorcsoportKezelõ> Members


        /// 
        /// <param name="csoport"></param>
        public bool Letrehoz(KorcsoportKezelõ csoport)
        {
            throw new NotImplementedException();
        }

        List<KorcsoportKezelõ> ICsoportKezelõ<KorcsoportKezelõ>.Listaz()
        {
            throw new NotImplementedException();
        }


        /// 
        /// <param name="csoport"></param>
        public bool Modosit(KorcsoportKezelõ csoport)
        {
            throw new NotImplementedException();
        }

        /// 
        /// <param name="csoport"></param>
        public bool Torol(KorcsoportKezelõ csoport)
        {
            throw new NotImplementedException();
        }

        #endregion
    }//end KorcsoportKezelõ

}//end namespace KorcsoportVezetõFunkciók