///////////////////////////////////////////////////////////
//  DbConnection.cs
//  Implementation of the Class DbConnection
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:08:10
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Entity;

using CampLogic.KorcsoportVezetoFunkciok;
using CampLogic.TaborvezetoFunkciok;
using CampLogic.IfjusagiVezetoFunkciok;
using CampLogic.Borders;


namespace CampLogic.Db
{
    public class MyDbConnection : DbContext
    {

        public MyDbConnection()
        {
            // Ha megváltozik a modell, ezzel magától eldobja az adatbét
            Database.SetInitializer<MyDbConnection>(new DropCreateDatabaseIfModelChanges<MyDbConnection>());
        }

        public DbSet<Csoport> Csoportok { get; set; }

        public DbSet<Haz> Hazak { get; set; }

        public DbSet<Korcsoport> Korcsoportok { get; set; }

        public DbSet<Szoba> Szobak { get; set; }

        public DbSet<Taborozo> Taborozok { get; set; }

        public DbSet<Turnus> Turnusok { get; set; }

        public DbSet<Vezeto> Vezetok { get; set; }

    }//end DbConnection

}//end namespace Db