///////////////////////////////////////////////////////////
//  DbConnection.cs
//  Implementation of the Class DbConnection
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:08:10
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Entity;

using KorcsoportVezetõFunkciók;
using TáborvezetõFunkciók;
using IfjúságiVezetõFunkciók;
using Borders;


namespace Db
{
    public class DbConnection : DbContext
    {

        public DbConnection()
        {

        }


        public DbSet<Csoport> Csoportok { get; set; }

        public DbSet<Ház> Házak { get; set; }

        public DbSet<Korcsoport> Korcsoportok { get; set; }

        public DbSet<Szoba> Szobák { get; set; }

        public DbSet<Táborozó> Táborozók { get; set; }

        public DbSet<Turnus> Turnusok { get; set; }

        public DbSet<Vezetõ> Vezetök { get; set; }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    modelBuilder.Entity<Vezetõ>()
        //        .Property
        //}

    }//end DbConnection

}//end namespace Db