// <auto-generated />
namespace CampLogic.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class vezetöRövidÖ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vezetöRövidÖ));
        
        string IMigrationMetadata.Id
        {
            get { return "201304301705100_vezetöRövidÖ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
