// <auto-generated />
namespace CampLogic.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class vezeto1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vezeto1));
        
        string IMigrationMetadata.Id
        {
            get { return "201304272220560_vezeto1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
