///////////////////////////////////////////////////////////
//  CsoportKezelõ.cs
//  Implementation of the Class CsoportKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:00
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using CampLogic.KorcsoportVezetoFunkciok;
using CampLogic.Db;
namespace CampLogic.KorcsoportVezetoFunkciok
{
    public class CsoportKezelo : ICsoportKezelõ<Csoport>
    {

        public MyDbConnection conn=new MyDbConnection();

        public CsoportKezelo()
        {

        }
        public bool Letrehoz(Csoport csoport)
        {
            conn.Csoportok.Add(csoport);
            conn.SaveChanges();
            return true;
        }

        public bool Letrehoz(Csoport csoport, Korcsoport korcsoport)
        {
            csoport.Korcsoport = conn.Korcsoportok.Find(korcsoport.KorcsoportId);
            conn.Csoportok.Add(csoport);
            conn.SaveChanges();
            return true;
        }

        public List<Csoport> Listaz()
        {
            return (from k in conn.Csoportok select k).ToList<Csoport>();
        }

        public bool Modosit(Csoport csoport)
        {
            conn.SaveChanges();
            return true;
        }

        public bool Modosit(Csoport csoport, Korcsoport korcsoport)
        {
            conn.SaveChanges();
            return true;
        }

        public bool Torol(Csoport csoport)
        {
            conn.Csoportok.Remove(csoport);
            conn.SaveChanges();
            return true;
        }
    }//end CsoportKezelõ

}//end namespace KorcsoportVezetõFunkciók