///////////////////////////////////////////////////////////
//  Korcsoport.cs
//  Implementation of the Class Korcsoport
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:01:00
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;


using CampLogic.TaborvezetoFunkciok;
using CampLogic.KorcsoportVezetoFunkciok;

namespace CampLogic.KorcsoportVezetoFunkciok
{
    public class Korcsoport
    {

        public Korcsoport()
        {

        }


        #region Adat kapcsolati tulajdonságok

        [Key]
        public int KorcsoportId { get; set; }

        public int? TurnusId { get; set; }
        public virtual Turnus Turnus { get; set; }
        public virtual List<Csoport> Csoportok { get; set; }

        #endregion


        

        public int KorosztalyAlsoKorlat { get; set; }

        public int KorosztalyFelsoKorlat { get; set; }

        public string Nev { get; set; }

        public string Orszag { get; set; }

        public override string ToString()
        {
            return Nev + " (" + Orszag + "/" + KorosztalyAlsoKorlat + "-" + KorosztalyFelsoKorlat + ")";
        }



    }//end Korcsoport

}//end namespace KorcsoportVezetõFunkciók