///////////////////////////////////////////////////////////
//  TáborozóKezelõ.cs
//  Implementation of the Class TáborozóKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:00:05
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using CampLogic.KorcsoportVezetoFunkciok;
using CampLogic.TaborvezetoFunkciok;
using CampLogic.IfjusagiVezetoFunkciok;
using CampLogic.Db;
namespace CampLogic.IfjusagiVezetoFunkciok {
	public class TaborozoKezelo {

		public MyDbConnection conn = new MyDbConnection();

		public TaborozoKezelo(){

		}

		/// 
		/// <param name="Taborozo"></param>
		/// <param name="csoport"></param>
		public bool CsoporthozRendeles(Taborozo taborozo, Csoport csoport){
            conn.Taborozok.Find(taborozo).Csoport = csoport;
            conn.SaveChanges();
			return true;
		}

		public List<Taborozo> TaborozoListazas(){
            return conn.Taborozok.ToList<Taborozo>();
		}

		/// 
		/// <param name="taborozo"></param>
		public bool TaborozoModositasa(Taborozo taborozo){
            conn.SaveChanges();
            return true;
		}

		/// 
		/// <param name="Táborozó"></param>
		/// <param name="Szoba"></param>
		public void TaborozoSzobahozRendeles(Taborozo Taboroza, Szoba Szoba){

		}

		/// 
		/// <param name="taborozo"></param>
		public bool TaborozoTorles(Taborozo taborozo){

			return false;
		}

		/// 
		/// <param name="ujTaborozo"></param>
		public bool UjTaborozo(Taborozo ujTaborozo){
            conn.Taborozok.Add(ujTaborozo);
            conn.SaveChanges();
			return true;
		}

	}//end TáborozóKezelõ

}//end namespace IfjúságiVezetõFunkciók