///////////////////////////////////////////////////////////
//  TáborozóImportKezelõ.cs
//  Implementation of the Class TáborozóImportKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:00:05
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using CampLogic.IfjusagiVezetoFunkciok;
namespace CampLogic.IfjusagiVezetoFunkciok {
	public class TaborozoImportKezelo {

		public Taborozo m_Táborozó;
		public TaborozoKezelo m_TáborozóKezelõ;

		public TaborozoImportKezelo(){

		}

		/// <param name="path"></param>
		public bool ImportFilebol(string path){

			return false;
		}

	}//end TáborozóImportKezelõ

}//end namespace IfjúságiVezetõFunkciók