///////////////////////////////////////////////////////////
//  IfjúságiVezetõiKezelõFelület.cs
//  Implementation of the Class IfjúságiVezetõiKezelõFelület
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:22
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using CampLogic.KorcsoportVezetoFunkciok;
using CampLogic.IfjusagiVezetoFunkciok;
using CampLogic.TaborvezetoFunkciok;


namespace CampLogic.Borders {
	public class IfjusagiVezetoiKezeloFelulet : IIfjusagiVezetoiKezelo {

		public TaborozoImportKezelo _TaborozoImportKezelo;
		public TaborozoKezelo _TaborozoKezelo;

		public IfjusagiVezetoiKezeloFelulet(){
            _TaborozoKezelo = new TaborozoKezelo();
		}

		/// 
		/// <param name="Taborozo"></param>
		/// <param name="csoport"></param>
		public bool CsoporthozRendeles(Taborozo taborozo, Csoport csoport){
            return _TaborozoKezelo.CsoporthozRendeles(taborozo, csoport);
		}

        /// 
        /// <param name="Táborozó"></param>
        /// <param name="Szoba"></param>
        public void TaborozoSzobahozRendeles(Taborozo taborozo, Szoba szoba)
        {
            _TaborozoKezelo.TaborozoSzobahozRendeles(taborozo, szoba);
        }

		/// 
		/// <param name="path"></param>
		public bool ImportFilebol(string path){
            return _TaborozoImportKezelo.ImportFilebol(path);
		}

        public List<Taborozo> TaborozoListazas() {
            return _TaborozoKezelo.TaborozoListazas();
		}

		/// 
		/// <param name="táborozó"></param>
		public bool TaborozoModositasa(Taborozo taborozo){
            return _TaborozoKezelo.TaborozoModositasa(taborozo);
		}

		/// 
		/// <param name="taborozo"></param>
		public bool TaborozoTorles(Taborozo taborozo){
            return _TaborozoKezelo.TaborozoTorles(taborozo);
		}

		///
		/// <param name="taborozo"></param>
		public bool UjTaborozo(Taborozo taborozo){
			return _TaborozoKezelo.UjTaborozo(taborozo);
		}

    }//end IfjúságiVezetõiKezelõFelület

}//end namespace Borders