///////////////////////////////////////////////////////////
//  IfjúságiVezetõiKezelõFelület.cs
//  Implementation of the Class IfjúságiVezetõiKezelõFelület
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:22
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using CampLogic.KorcsoportVezetõFunkciók;
using CampLogic.IfjúságiVezetõFunkciók;
using CampLogic.TáborvezetõFunkciók;


namespace CampLogic.Borders {
	public class IfjúságiVezetõiKezelõFelület : IIfjúságiVezetõiKezelõ {

		public TáborozóImportKezelõ m_TáborozóImportKezelõ;
		public TáborozóKezelõ m_TáborozóKezelõ;

		public IfjúságiVezetõiKezelõFelület(){

		}

		/// 
		/// <param name="Taborozo"></param>
		/// <param name="csoport"></param>
		public bool CsoporthozRendeles(Táborozó Taborozo, Csoport csoport){

			return false;
		}

		/// 
		/// <param name="path"></param>
		public bool ImportFilebol(string path){

			return false;
		}

		public List<Táborozó> TaborozoListazas(){

			return null;
		}

		/// 
		/// <param name="táborozó"></param>
		public bool TaborozoModositasa(Táborozó táborozó){

			return false;
		}

		/// 
		/// <param name="Táborozó"></param>
		/// <param name="Szoba"></param>
		public void TáborozóSzobáhozRendelés(Táborozó Táborozó, Szoba Szoba){

		}

		/// 
		/// <param name="taborozo"></param>
		public bool TaborozoTorles(Táborozó taborozo){

			return false;
		}

		/// 
		/// <param name="taborozo"></param>
		public bool UjTaborozo(Táborozó taborozo){

			return false;
		}

    }//end IfjúságiVezetõiKezelõFelület

}//end namespace Borders