///////////////////////////////////////////////////////////
//  IIfjúságiVezetõiKezelõ.cs
//  Implementation of the Interface IIfjúságiVezetõiKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:22
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using KorcsoportVezetõFunkciók;
using IfjúságiVezetõFunkciók;
namespace Borders {
	public interface IIfjúságiVezetõiKezelõ {

		/// 
		/// <param name="csoport"></param>
        bool CsoporthozRendeles(Táborozó Taborozo, Csoport csoport);

		/// 
		/// <param name="path"></param>
		bool ImportFilebol(string path);

		List<Táborozó> TaborozoListazas();

		/// 
		/// <param name="táborozó"></param>
		bool TaborozoModositasa(Táborozó táborozó);

		/// 
		/// <param name="taborozo"></param>
		bool TaborozoTorles(Táborozó taborozo);

		/// 
		/// <param name="taborozo"></param>
		bool UjTaborozo(Táborozó taborozo);
	}//end IIfjúságiVezetõiKezelõ

}//end namespace Borders