///////////////////////////////////////////////////////////
//  IKorcsoportVezetõiKezelõ.cs
//  Implementation of the Interface IKorcsoportVezetõiKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:22
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using CampLogic.KorcsoportVezetõFunkciók;
using CampLogic.Borders;
namespace CampLogic.Borders {
	public interface IKorcsoportVezetoiKezelo : IIfjusagiVezetoiKezelo {

		/// 
		/// <param name="csoport"></param>
		bool CsoportLetrehozas(Csoport csoport);

		/// 
		/// <param name="csoport"></param>
		bool CsoportModositas(Csoport csoport);

		/// 
		/// <param name="csoport"></param>
		bool CsoportTorles(Csoport csoport);

		/// 
		/// <param name="korcsoport"></param>
		bool KorcsoportLetrehozas(Korcsoport korcsoport);

		/// 
		/// <param name="korcsoport"></param>
		bool KorcsoportModositas(Korcsoport korcsoport);

		/// 
		/// <param name="korcsoport"></param>
		bool KorcsoportTorles(Korcsoport korcsoport);
	}//end IKorcsoportVezetõiKezelõ

}//end namespace Borders