///////////////////////////////////////////////////////////
//  ITáborvezetõiKezelõ.cs
//  Implementation of the Interface ITáborvezetõiKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:22
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using CampLogic.TáborvezetõFunkciók;
using CampLogic.Borders;
namespace CampLogic.Borders
{
    public interface ITáborvezetoiKezelo : IKorcsoportVezetoiKezelo
    {

        /// 
        /// <param name="haz"></param>
        bool HazLetrehozas(Ház haz);

        List<Ház> HazListazas();

        /// 
        /// <param name="haz"></param>
        bool HazModositas(Ház haz);

        /// 
        /// <param name="haz"></param>
        bool HazTorles(Ház haz);

        Statisztika StatisztikaHanyOrszagPerTurnus();

        Statisztika StatisztikaHanyTaborozóPerTurnus();

        /// 
        /// <param name="haz"></param>
        /// <param name="szoba"></param>
        bool SzobaLetrehozas(Ház haz, Szoba szoba);

        /// 
        /// <param name="haz"></param>
        List<Szoba> SzobaListazas(Ház haz);

        List<Szoba> SzobaListazas();

        /// 
        /// <param name="haz"></param>
        /// <param name="szoba"></param>
        bool SzobaModositas(Ház haz, Szoba szoba);

        /// 
        /// <param name="haz"></param>
        /// <param name="szoba"></param>
        bool SzobaTorol(Ház haz, Szoba szoba);

        /// 
        /// <param name="turnus"></param>
        bool TurnusLetrehozas(Turnus turnus);

        List<Turnus> TurnusListazas();

        /// 
        /// <param name="turnus"></param>
        bool TurnusModositas(Turnus turnus);


    }//end ITáborvezetõiKezelõ

}//end namespace Borders