///////////////////////////////////////////////////////////
//  IVezetõ.cs
//  Implementation of the Interface IVezetõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:23
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using CampLogic.Borders;
namespace CampLogic.Borders {
	public interface IVezeto {

		string Jelszo{
			get;
			set;
		}

		string Nev{
			get;
			set;
		}
	}//end IVezetõ

}//end namespace Borders