///////////////////////////////////////////////////////////
//  KorcsoportVezetõiKezelõFelület.cs
//  Implementation of the Class KorcsoportVezetõiKezelõFelület
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:23
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using KorcsoportVezetõFunkciók;
using Borders;
namespace Borders {
	public class KorcsoportVezetõiKezelõFelület : IfjúságiVezetõiKezelõFelület, IKorcsoportVezetõiKezelõ {

		public KorcsoportKezelõ m_KorcsoportKezelõ;
		public CsoportKezelõ m_CsoportKezelõ;

		public KorcsoportVezetõiKezelõFelület(){

		}

		~KorcsoportVezetõiKezelõFelület(){

		}

		/// 
		/// <param name="csoport"></param>
		public bool CsoportLetrehozas(Csoport csoport){

			return false;
		}

		/// 
		/// <param name="csoport"></param>
		public bool CsoportModositas(Csoport csoport){

			return false;
		}

		/// 
		/// <param name="csoport"></param>
		public bool CsoportTorles(Csoport csoport){

			return false;
		}

		/// 
		/// <param name="korcsoport"></param>
		public bool KorcsoportLetrehozas(Korcsoport korcsoport){

			return false;
		}

		/// 
		/// <param name="korcsoport"></param>
		public bool KorcsoportModositas(Korcsoport korcsoport){

			return false;
		}

		/// 
		/// <param name="korcsoport"></param>
		public bool KorcsoportTorles(Korcsoport korcsoport){

			return false;
		}

	}//end KorcsoportVezetõiKezelõFelület

}//end namespace Borders