///////////////////////////////////////////////////////////
//  KorcsoportVezetõiKezelõFelület.cs
//  Implementation of the Class KorcsoportVezetõiKezelõFelület
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:23
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using CampLogic.KorcsoportVezetoFunkciok;
using CampLogic.Borders;
namespace CampLogic.Borders {
	public class KorcsoportVezetoiKezeloFelulet : IfjusagiVezetoiKezeloFelulet, IKorcsoportVezetoiKezelo {

		public KorcsoportKezelo m_KorcsoportKezelo=new KorcsoportKezelo();
		public CsoportKezelo m_CsoportKezelo=new CsoportKezelo();

		public KorcsoportVezetoiKezeloFelulet(){

		}

		~KorcsoportVezetoiKezeloFelulet(){

		}

		/// 
		/// <param name="csoport"></param>
		public bool CsoportLetrehozas(Csoport csoport){

            return m_CsoportKezelo.Letrehoz(csoport); ;
		}

		/// 
		/// <param name="csoport"></param>
		public bool CsoportModositas(Csoport csoport){

			return m_CsoportKezelo.Modosit(csoport);
		}

		/// 
		/// <param name="csoport"></param>
		public bool CsoportTorles(Csoport csoport){

			return m_CsoportKezelo.Torol(csoport);
		}

		/// 
		/// <param name="korcsoport"></param>
		public bool KorcsoportLetrehozas(Korcsoport korcsoport){

			return m_KorcsoportKezelo.Letrehoz(korcsoport);
		}

		/// 
		/// <param name="korcsoport"></param>
		public bool KorcsoportModositas(Korcsoport korcsoport){

			return m_KorcsoportKezelo.Modosit(korcsoport);
		}

		/// 
		/// <param name="korcsoport"></param>
		public bool KorcsoportTorles(Korcsoport korcsoport){

			return m_KorcsoportKezelo.Torol(korcsoport);
		}


        public List<Korcsoport> KorcsoportListazas()
        {
            return m_KorcsoportKezelo.Listaz();
        }

        public List<Csoport> CsoportListazas()
        {
            return m_CsoportKezelo.Listaz();
        }
    }//end KorcsoportVezetõiKezelõFelület

}//end namespace Borders