///////////////////////////////////////////////////////////
//  TáborvezetõiKezelõFelület.cs
//  Implementation of the Class TáborvezetõiKezelõFelület
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:23
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using CampLogic.TáborvezetõFunkciók;
using CampLogic.Borders;
namespace CampLogic.Borders
{
    public class TáborvezetoiKezeloFelulet : KorcsoportVezetoiKezeloFelület, ITáborvezetoiKezelo
    {

        private SzobaKezelo _SzobaKezelõ;
        private TurnusKezelõ _TurnusKezelõ;
        private HázKezelo _HázKezelõ;
        private StatisztikaKazelo _StatisztikaKazelõ;

        public TáborvezetoiKezeloFelulet()
        {
            _SzobaKezelõ = new SzobaKezelo();
            _TurnusKezelõ = new TurnusKezelõ();
            _HázKezelõ = new HázKezelo();
            _StatisztikaKazelõ = new StatisztikaKazelo();
        }


        /// 
        /// <param name="haz"></param>
        public bool HazLetrehozas(Ház haz)
        {
            return _HázKezelõ.HázLetrehozas(haz);
        }

        public List<Ház> HazListazas()
        {
            return _HázKezelõ.HazListazas();
        }

        /// 
        /// <param name="haz"></param>
        public bool HazModositas(Ház haz)
        {
            return _HázKezelõ.HázModositas(haz);
        }

        /// 
        /// <param name="haz"></param>
        public bool HazTorles(Ház haz)
        {
            return _HázKezelõ.HazTorles(haz);
        }

        public Statisztika StatisztikaHanyOrszagPerTurnus()
        {
            return _StatisztikaKazelõ.HanyOrszagPerTurnus();
        }

        public Statisztika StatisztikaHanyTaborozóPerTurnus()
        {
            return _StatisztikaKazelõ.HanyTaborozóPerTurnus();
        }

        /// 
        /// <param name="haz"></param>
        /// <param name="szoba"></param>
        public bool SzobaLetrehozas(Ház haz, Szoba szoba)
        {
            return _SzobaKezelõ.SzobaLetrehozas(haz, szoba);
        }

        /// 
        /// <param name="haz"></param>
        public List<Szoba> SzobaListazas(Ház haz)
        {
            return _SzobaKezelõ.SzobaListazas(haz);
        }

        public List<Szoba> SzobaListazas()
        {
            return _SzobaKezelõ.SzobaListazas();
        }

        /// 
        /// <param name="haz"></param>
        /// <param name="szoba"></param>
        public bool SzobaModositas(Ház haz, Szoba szoba)
        {
            return _SzobaKezelõ.SzobaModositas(haz, szoba);

        }

        /// 
        /// <param name="haz"></param>
        /// <param name="szoba"></param>
        public bool SzobaTorol(Ház haz, Szoba szoba)
        {
            return _SzobaKezelõ.SzobaTorles(szoba);
        }

        /// 
        /// <param name="turnus"></param>
        public bool TurnusLetrehozas(Turnus turnus)
        {
            return _TurnusKezelõ.TurnusLetrehozas(turnus);
        }

        public List<Turnus> TurnusListazas()
        {
            return _TurnusKezelõ.TurnusListazas();
        }

        /// 
        /// <param name="turnus"></param>
        public bool TurnusModositas(Turnus turnus)
        {
            return _TurnusKezelõ.TurnusModositas(turnus);
        }

    }//end TáborvezetõiKezelõFelület

}//end namespace Borders