///////////////////////////////////////////////////////////
//  Vezetõ.cs
//  Implementation of the Class Vezetõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:23
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using Borders;
using System.ComponentModel.DataAnnotations;
namespace Borders
{
    public class Vezetõ : IVezetõ
    {

        public Vezetõ()
        {

        }


        #region Adat kapcsolati tulajdonságok

        [Key]
        public int VezetõId { get; set; }

        #endregion


        public string Jelszo { get; set; }

        public string Nev { get; set; }


        public int TipusSzam { get; set; }

        public VezetõTípus Tipus
        {
            get
            {
                return (VezetõTípus)TipusSzam;
            }
            set
            {
                TipusSzam = (int)value;
            }
        }


        public override string ToString()
        {
            return Nev;
        }

    }//end Vezetõ

}//end namespace Borders