///////////////////////////////////////////////////////////
//  Vezetõ.cs
//  Implementation of the Class Vezetõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:23
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using Borders;
namespace Borders {
	public class Vezetõ : IVezetõ {

		public Vezetõ(){

		}

		~Vezetõ(){

		}

		public string Jelszo{ get; set; }

		public string Nev{ get; set; }

		public VezetõTípus Tipus{
			get{
				return Tipus;
			}
			set{
				Tipus = value;
			}
		}

		public int VezetõId{ get; set; }

	}//end Vezetõ

}//end namespace Borders