///////////////////////////////////////////////////////////
//  VezetõTípus.cs
//  Implementation of the Class VezetõTípus
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 19:57:23
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



namespace CampLogic.Borders {
	public enum VezetõTípus : int {

		IfjúságiVezetõ,
		KorcsoportVezetõ,
		TáborVezetõ

	}//end VezetõTípus

}//end namespace Borders