///////////////////////////////////////////////////////////
//  TáborozóKezelõ.cs
//  Implementation of the Class TáborozóKezelõ
//  Generated by Enterprise Architect
//  Created on:      26-ápr.-2013 20:00:05
//  Original author: lovi88
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;



using CampLogic.KorcsoportVezetõFunkciók;
using CampLogic.TáborvezetõFunkciók;
using CampLogic.IfjúságiVezetõFunkciók;
using CampLogic.Db;
namespace CampLogic.IfjúságiVezetõFunkciók {
	public class TáborozóKezelo {

		public MyDbConnection conn = new MyDbConnection();

		public TáborozóKezelo(){

		}

		~TáborozóKezelo(){

		}

		/// 
		/// <param name="Taborozo"></param>
		/// <param name="csoport"></param>
		public bool CsoporthozRendeles(Táborozó Taborozo, Csoport csoport){

			return false;
		}

		public List<Táborozó> TaborozoListazas(){

			return null;
		}

		/// 
		/// <param name="taborozo"></param>
		public bool TaborozoModositasa(Táborozó taborozo){

			return false;
		}

		/// 
		/// <param name="Táborozó"></param>
		/// <param name="Szoba"></param>
		public void TáborozóSzobáhozRendelés(Táborozó Táborozó, Szoba Szoba){

		}

		/// 
		/// <param name="taborozo"></param>
		public bool TaborozoTorles(Táborozó taborozo){

			return false;
		}

		/// 
		/// <param name="ujTaborozo"></param>
		public bool UjTaborozo(Táborozó ujTaborozo){

			return false;
		}

	}//end TáborozóKezelõ

}//end namespace IfjúságiVezetõFunkciók